### ISSUE TITLE
Add project config

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/password-manager#14]
**Tasks:**

- [ ] Add Husky
- [ ] Add lint-staged
- [ ] Add eslint config
- [ ] Add prettier config
- [ ] Add TypeScript paths (aliases)
