### ISSUE TITLE
Add database hooks for CURD

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/password-manager#9]
Add CRUD hooks with Firebase

**Todo list**

- [x] Create doc
- [x] Read collection
- [x] Read doc from collection
- [x] Read collection with `where`
- [x] Update doc from collection using ID
- [x] Delete doc from collection usign ID
